### ISSUE TITLE
error in the website

### ISSUE THREAD

**Issue by TuuSiwei** [kaiban-ai/KaibanJS#107]
I follow the instruction in readme，and the following error occurred：
![image](https://github.com/user-attachments/assets/2d4c621d-268d-4745-9b90-ac1ad6745352)

**Comment by darielnoel** [comment]
Thanks for reporting this. Checking this out now.

**Comment by darielnoel** [comment]
Just to make sure:

 you did

![image](https://github.com/user-attachments/assets/26e18c28-400c-42be-a214-275a31b20d3b)

Are you using Windows right? Which version?

**Comment by TuuSiwei** [comment]
yes, I follow the three steps

version info:
![image](https://github.com/user-attachments/assets/40f64735-4ee8-4589-b12e-07b27c165755)

**Comment by darielnoel** [comment]
Do you have chance for a quick video Call? It will be great to be able to debug it with you in real time

https://www.kaibanjs.com/discord

**Comment by darielnoel** [comment]
Just DM me there.

**Comment by TuuSiwei** [comment]
I'm sorry that I can't use discord in China because SMS verification is not supported

**Comment by darielnoel** [comment]
> I'm sorry that I can't use discord in China because SMS verification is not supported

No worries. What about Google Meets? or any other you think may work?

**Comment by TuuSiwei** [comment]
sorry，I made some mistakes. I have joint the discord.what should I do? invite?
![image](https://github.com/user-attachments/assets/8124af44-5f73-431f-8ff7-0d5dacba710f)

**Comment by darielnoel** [comment]
Amazing. Let's connect there.

**Comment by darielnoel** [comment]
Hi @TuuSiwei, We’ve resolved the issue in our recent session. Thanks for your collaboration! I’ll close this issue now, but feel free to reopen if anything else comes up.
