### ISSUE TITLE
[BUG] - Teams.js file not recognized inside src folder

### ISSUE THREAD

**Issue by dannleft** [kaiban-ai/KaibanJS#166]
#### Describe the Bug:
When configuring teams in KaibanJS locally, the `teams.js` file is only recognized if it is located in the root directory and has a `.kban.js` extension. Files placed inside the `src` directory or other subdirectories (e.g., `src/blogTeam.js`) are not recognized, even when they contain valid configurations.

#### KaibanJS Team Config:
The issue occurs during local testing of KaibanJS. The structure of the project includes:
- A `.kaiban` folder in the root directory.
- A `team.kban.js` file in the root directory that is recognized correctly.
- Multiple `teams.js` configurations within the `src` directory (e.g., `src/blogTeam.js` and `src/quoteTeam.js`), which are not detected by KaibanJS.

#### Steps to Reproduce:
1. Create a `blogTeam.js` or `quoteTeam.js` file inside the `src` directory with valid team configuration for KaibanJS.
2. Run KaibanJS locally and observe that these files are not detected.
3. Move the same configuration file to the root directory and rename it to `team.kban.js`.
4. Run KaibanJS again and confirm that the file is now recognized.

#### Current vs. Expected Behavior:
**Current behavior:** KaibanJS only recognizes team configuration files located in the root directory with the `.kban.js` extension. Files in the `src` directory or other subdirectories are ignored.  
**Expected behavior:** KaibanJS should recognize team configuration files located within the `src` directory or subdirectories without requiring them to be in the root directory.

#### Environment:
- **Framework/Library:** NodeJS, Vanilla JavaScript  
- **KaibanJS Version:** 0.1.0 (example, adjust as necessary)  
- **JavaScript Runtime:** NodeJS v16.x (example, adjust as necessary)  
- **Operating System:** (e.g., macOS Monterey, Windows 10, Ubuntu 20.04)

**Comment by darielnoel** [comment]
Disregard.
