### ISSUE TITLE
[BUG] - .env file gets deleted after running KaibanJS

### ISSUE THREAD

**Issue by dannleft** [kaiban-ai/KaibanJS#167]
#### Describe the Bug:
When running KaibanJS locally, the `.env` file inside the `.kaiban` folder is overwritten by the `.env` file located in the project's root directory. This behavior occurs when both files are present and contain environment variables, which leads to the loss of the intended configuration inside the `.kaiban` folder.

#### KaibanJS Team Config:
The issue occurs in a standard local setup for KaibanJS where:
- A `.env` file exists in the project root directory.
- A separate `.env` file is present in the `.kaiban` folder.

#### Steps to Reproduce:
1. Create a `.env` file in the root directory with valid environment variables.
2. Create another `.env` file in the `.kaiban` folder with a different set of valid environment variables.
3. Run KaibanJS locally.
4. Observe that the `.env` file inside the `.kaiban` folder is overwritten by the content of the root `.env` file.

#### Current vs. Expected Behavior:
**Current behavior:**  
The `.env` file inside the `.kaiban` folder is overwritten by the `.env` file in the root directory when KaibanJS runs.  

**Expected behavior:**  
KaibanJS should prioritize the `.env` file in the `.kaiban` folder for configurations specific to KaibanJS and avoid overwriting it with the root `.env` file. Both files should coexist without interference.

#### Environment:
- **Framework/Library:** Node.js, Vanilla JavaScript  
- **KaibanJS Version:** (e.g., 0.1.0 - adjust as necessary)  
- **JavaScript Runtime:** (e.g., Node.js v16.x - adjust as necessary)  
- **Operating System:** (e.g., macOS Monterey, Windows 10, Ubuntu 20.04 - adjust as necessary)  

#### Additional Context:
This issue can cause significant confusion and potential misconfigurations, especially when users rely on separate `.env` files for project-wide and KaibanJS-specific environment variables.

**Comment by darielnoel** [comment]
Thank you for bringing this up! This is actually the expected behavior, as the .env file in the project root is prioritized over the one in the .kaiban folder. To avoid conflicts, please ensure all critical variables are defined in the root .env file. We appreciate your understanding!
