### ISSUE TITLE
[DOC ISSUE] - Insufficient documentation for integrating KaibanJS with custom endpoints (e.g., LM Studio)

### ISSUE THREAD

**Issue by dannleft** [kaiban-ai/KaibanJS#168]
### Describe the Issue

This one is related also to #94 

The current documentation lacks clear guidance on integrating KaibanJS with custom endpoints, such as LM Studio. Users face the following challenges:

- Configuring `apiBaseUrl` and `apiKey` for external endpoints.
- Understanding how to set up proxies or adapt them for non-default APIs.
- Troubleshooting common issues like CORS errors and payload formatting problems.

This gap in documentation makes it difficult for users to adapt KaibanJS for use cases involving custom API endpoints or models.

### Doc URL

Documentation URL: [**KaibanJS Documentation: Custom Integrations**](https://docs.kaibanjs.com/category/custom-integrations)

**Comment by darielnoel** [comment]
Thank you for the feedback! We will work on adding documentation for integrating KaibanJS with custom endpoints like LM Studio. Stay

**Comment by darielnoel** [comment]
Added LM Studio integration docs.

https://docs.kaibanjs.com/llms-docs/custom-integrations/LM-Studio
