### ISSUE TITLE
[BUG] - Validation and error handling issues with payloads sent to custom APIs

### ISSUE THREAD

**Issue by dannleft** [kaiban-ai/KaibanJS#170]
### Describe the Bug

When sending payloads to custom APIs like LM Studio, KaibanJS does not validate the payload structure properly. This can result in errors such as missing required fields (e.g., `messages`), leading to failed requests. Additionally, errors like CORS issues are not well-documented or handled, which complicates troubleshooting for users.

### KaibanJS Team Config

This issue occurs when attempting to integrate KaibanJS with a custom API, such as LM Studio, and using a payload that does not conform to the expected structure. Example payload:

```json
{
  "model": "lmstudio-community/Meta-Llama-3.1-8B-Instruct-GGUF",
  "temperature": 1,
  "top_p": 1,
  "frequency_penalty": 0,
  "presence_penalty": 0,
  "n": 1,
  "stream": false,
  "messages": [
    {
      "role": "system",
      "content": "System message content."
    },
    {
      "role": "user",
      "content": "User message content."
    }
  ]
}
```

### Steps to Reproduce

1. Configure KaibanJS to send requests to a custom API endpoint (e.g., LM Studio).
2. Provide a payload missing a required field (e.g., `messages`) or with an incorrect structure.
3. Attempt to send a request through KaibanJS.
4. Observe the error returned by the API (e.g., "Field 'messages' is required").

### Current vs. Expected Behavior

**Current behavior**: Requests fail due to unvalidated or incorrectly structured payloads, and errors like CORS are not clearly surfaced to the user.

**Expected behavior**: 
- Payloads should be validated before being sent to the API.
- Errors should include clear, actionable messages for users.
- CORS issues should have troubleshooting steps in the documentation or mitigations in the code.

### Environment

- **Framework/Library**: Vanilla JavaScript
- **KaibanJS Version**: [e.g., 0.1.0]
- **JavaScript Runtime**: NodeJS, Chrome
- **OS**: Windows 10/11, Linux

**Comment by darielnoel** [comment]
Disregard. It was a missconfiguration on LLMStudio
