### ISSUE TITLE
Expand Tool Integration Capabilities in AgenticJS Playground

### ISSUE THREAD

**Issue by dannleft** [kaiban-ai/KaibanJS#26]
**Is your feature request related to a problem? Please describe.**
Yes, the problem is with the AgenticJS playground on the website, which currently restricts users to only one predefined tool (TavilySearchResults) for testing example use cases. This limitation does not align with the capabilities available when running AgenticJS locally, where any tool from the LangChain community can be integrated.

**Describe the solution you'd like**
I propose enhancing the AgenticJS playground on the website to allow users to select and integrate various tools, similar to the flexibility provided in the local setup. This could be implemented via a dropdown menu or an interface where users can select which tools they want to integrate into their testing session.

**Describe alternatives you've considered**
A simpler alternative might involve providing multiple pre-configured projects within the playground, each configured with different tools. This would allow users to select a project setup that best matches their interests or testing needs without the need for backend changes to the playground's tool integration logic.

**Additional context**
Enabling broader tool integration in the online playground would not only enhance user experience by providing greater flexibility but also better showcase the versatility and power of AgenticJS. This improvement would make the playground more valuable for demonstrations and educational purposes, aligning more closely with the open-source community's standards of flexibility and innovation.

**Comment by darielnoel** [comment]
+1 @OdinSweng

**Comment by OdinSweng** [comment]
Thank you, @dannleft. We definitely need to allow the use of more tools in the Playground. We will be incorporating them soon, and we’ve been evaluating options. Initially, we will define a list, and then we can continue adding more, especially the ones that are most requested.

At this moment, I don't think we will allow adding the tools through a selector when we incorporate the rest. The idea is to use the editor to write the code and preview what it's doing. It shouldn't be defined and used in different ways. That idea is good, but it would be more suitable if we allowed everything to be created with clicks

**Comment by OdinSweng** [comment]
I’m pleased to announce that an initial set of tools has been incorporated and is now available for use. For more information, you can check out the [KaibanJS documentation](https://docs.kaibanjs.com/category/tools-docs).

In the near future, we’ll be adding more tools, especially those that enable RAG (Retrieve and Generate). We’ll also be open to suggestions for tools to incorporate in future updates.
