### ISSUE TITLE
[WEBSITE ISSUE] - Incorrect Library Import in Code Examples on Main Page

### ISSUE THREAD

**Issue by dannleft** [kaiban-ai/KaibanJS#61]
### Describe the Issue
There is an incorrect import statement in the code examples provided on the KaibanJS website. Specifically, in the examples shown under the "Real Use Cases: You Can Develop Now!" section (including AI Agents for Sports News, Trip Planning, and Resume Building), the code incorrectly imports the library `AgenticJS` instead of the correct `KaibanJS`. This could lead to confusion or errors when users attempt to follow the examples.

### URL
[https://www.kaibanjs.com/](https://www.kaibanjs.com/)

### Steps to Reproduce
1. Go to the KaibanJS website at [https://www.kaibanjs.com/](https://www.kaibanjs.com/).
2. Scroll down to the section titled "Real Use Cases: You Can Develop Now!".
3. Click on any of the provided examples (e.g., AI Agents for Sports News).
4. Review the code snippet provided.
5. Observe that the import statement incorrectly uses `AgenticJS` instead of `KaibanJS`.

### Expected Behavior
The code snippets provided in the examples should import `KaibanJS` correctly, reflecting the library's proper usage.

### Screenshots
![image](https://github.com/user-attachments/assets/455124b4-1411-4594-bfa8-b1337c077934)

<img width="431" alt="image" src="https://github.com/user-attachments/assets/9a84d50c-728b-40e6-8cd3-7bb043821f47">

### Possible Solution
The import statement in all relevant code examples should be corrected to:
```javascript
import { Agent, Task, Team } from 'kaibanjs';
```

### Additional Context
This issue affects the examples shown on the website, potentially causing confusion for developers who are trying to use these examples to learn or develop their own projects using KaibanJS.

### Environment Details
- Browser: Chrome Version 116.0.5845.96
- Operating System: Windows 11
- Screen Resolution: 1920x1080
- Device: Desktop

**Comment by OdinSweng** [comment]
Hi @dannleft thank you for your report. We want to inform you that the issue with the incorrect import statement in the code examples has been corrected. Now, all examples correctly reference KaibanJS instead of AgenticJS.
