### ISSUE TITLE
[DOC ISSUE] - Incorrect Discord community link in KaibanJS documentation

### ISSUE THREAD

**Issue by dannleft** [kaiban-ai/KaibanJS#64]
### Describe the Issue
The Discord community link in the KaibanJS documentation currently redirects to an outdated server. The URL used is `https://bit.ly/JoinAIChamps`, which leads to the AI Champions server instead of the KaibanJS community.

### Expected Behavior
The link should redirect to the correct KaibanJS Discord community. The correct URL that should be used is `https://kaibanjs.com/discord`.

### Doc URL
📚 Official Documentation: https://docs.kaibanjs.com/

<img width="1245" alt="image" src="https://github.com/user-attachments/assets/be061b42-50d5-4166-8306-50c85fb3c2bd">

**Comment by darielnoel** [comment]
Solved.
