### ISSUE TITLE
Add ESLint and Prettier Configuration to Project

### ISSUE THREAD

**Issue by darielnoel** [kaiban-ai/KaibanJS#69]
**Is your feature request related to a problem? Please describe.**
Currently, the project lacks configuration for ESLint and Prettier, which are essential for maintaining consistent code style and enforcing best practices. Without these tools, developers might introduce stylistic or structural inconsistencies, making collaboration and code review more difficult.

**Describe the solution you'd like**
Integrate ESLint and Prettier into the project with a set of rules tailored to the project's code style. This would ensure that code formatting and linting are enforced consistently across all contributions. It would be beneficial to configure Prettier to run automatically on file save and ESLint as part of the pre-commit hook to catch issues early.

**Describe alternatives you've considered**
An alternative would be to manually enforce code style during reviews, but this is error-prone and time-consuming. Automating code style checks with ESLint and Prettier would streamline the process.

**Comment by kedar1998** [comment]
I would like to add eslint and prettier. Can you assign it to me

**Comment by darielnoel** [comment]
Thank you so much, @kedar1998.  This issue had slipped through my radar; apologies for that. 

@alienkarma is already addressing it in PR #82. 

However, if you're interested in contributing, the discussion at [Issue #31](https://github.com/kaiban-ai/KaibanJS/issues/31) would be a great starting point. 

Thanks again, and sorry for the oversight!

**Comment by darielnoel** [comment]
Related to PR #82
