### ISSUE TITLE
[DOC ISSUE] - Add a Next.js Example to KaibanJS Documentation

### ISSUE THREAD

**Issue by dannleft** [kaiban-ai/KaibanJS#91]
### Describe the Issue
Currently, the documentation provides a tutorial for integrating KaibanJS with React using Vite. However, many developers use Next.js to build their applications, and it would be helpful to have a clear example or guide for setting up and integrating KaibanJS with Next.js.

This example could follow a structure similar to the existing React tutorial, covering the project setup, installation of dependencies, defining agents, and handling tasks within a Next.js application.

Including a Next.js-specific example would make the documentation more comprehensive and accessible to developers who use that framework.

### Doc URL
This suggestion is related to the section "React + AI Agents (Tutorial)" in the documentation: https://docs.kaibanjs.com/react-tutorial. **And the idea is to do something similar but with Next.js + AI Agents (Tutorial), which does not exist in the documentation.**

**Comment by darielnoel** [comment]
Done https://docs.kaibanjs.com/get-started/Tutorial:%20Next.js%20+%20AI%20Agents
