### ISSUE TITLE
[DOC ISSUE] - Add OpenRouter Integration Documentation

### ISSUE THREAD

**Issue by dannleft** [kaiban-ai/KaibanJS#94]
### Describe the Issue
The documentation needs to be updated to include details on the integration of OpenRouter into KaibanJS. This integration allows developers to easily access multiple AI models through a single API endpoint. The documentation should highlight the benefits of this integration and provide clear instructions on how to configure and use OpenRouter within KaibanJS.

### Doc URL
N/A (This is a new section that needs to be added to the existing documentation).

**Comment by gregid** [comment]
I would add the info to include model in the config, e.g.:
```js
// Define an agent configured with OpenRouter
const profileAnalyst = new Agent({
   name: 'Mary',
   role: 'Profile Analyst',
   goal: 'Extract structured information from conversational user input.',
   background: 'Data Processor',
   tools: [],
   llmConfig: {
     provider: "openai",
     model: "meta-llama/llama-3.1-8b-instruct:free", // <- example; use the exact model name from OpenRouter website
     apiBaseUrl: "https://openrouter.ai/api/v1",
     apiKey: 'YOUR_API_KEY' // best handled via an environment variable
   }
});

```

**Comment by darielnoel** [comment]
✅ Tarde pero seguro! OpenRouter docs are now live - better late than never! 🚀

https://docs.kaibanjs.com/llms-docs/custom-integrations/OpenRouter
